// IMPORTER LES OUTILS REACT

// IMPORTER NOTRE PREMIER COMPOSANT: APP

// CIBLER LA DIV DONT L'ID EST ROOT

// CREER UN NOEUD RACINE REACT A PARTIR DE LA DIV ROOT

// INJECTER NOTRE PREMIER COMPOSANT LE NOEUD RACINE
